#!/bin/bash -e

command="install"
if [[ $# -gt 0 ]]; then
  command="$1"
  shift
fi

if [[ $command == packages ]]; then

  # echo all the packages we are dependent on
  echo "build-essential"

elif [[ $command == install ]]; then

  # Install packages
  sudo apt-get update && sudo apt-get install -y "$($0 packages)"

  mkdir -p ~/zz_packages && cd $_
  curl 'http://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz' | tar -xzv
  cd ruby-2.4.0/

  ./configure && make -j`grep -c ^processor /proc/cpuinfo` && sudo make install
fi

