#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $no_ruby ]] && exit 0

if [[ $command == packages ]]; then

  # echo all the packages we are dependent on
  echo "build-essential"

elif [[ $command == install ]]; then

  if jsaws-build-block "ruby" "Installing Ruby"; then
    if ! which ruby > /dev/null; then

      # Install packages
      sudo apt-get update && sudo apt-get install -y "$($0 --command=packages)"

      mkdir -p ~/zz_packages && cd $_
      curl 'http://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.gz' | tar -xzv
      cd ruby-2.4.0/

      ./configure && make -j`grep -c ^processor /proc/cpuinfo` && sudo make install
    fi

    jsaws-build-block "ruby" "done"
  fi

else

  # Did not understand the command -- just default to installing
  $0 --command=install "$@"
fi

