#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $no_jenkins ]] && exit 0
[[ -z $jenkins    ]] && exit 0

# ---------- Jenkins ----------
if jsaws-build-block "jenkins" "Installing Jenkins"; then

  if ! which dot > /dev/null; then

    sudo DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:openjdk-r/ppa
    sudo DEBIAN_FRONTEND=noninteractive apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y graphviz openjdk-7-jdk

    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    echo 'deb https://pkg.jenkins.io/debian-stable binary/' | tee -a /etc/apt/sources.list

    sudo DEBIAN_FRONTEND=noninteractive apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y jenkins

    systemctl start jenkins

    # TODO: test that jenkins is listening on 8080

    echo cat /var/lib/jenkins/secrets/initialAdminPassword
    cat /var/lib/jenkins/secrets/initialAdminPassword

    # TODO: instructions for nginx-as-reverse-proxy-for-jenkins: https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu
  fi

  jsaws-build-block "jenkins" "Installing Jenkins"
fi


